### ISSUE TITLE
codepoints unreadable as they're pressed to the terminal's left margin

### ISSUE THREAD

**Issue by christianparpart** [hackerb9/ugrep#5]
A little spacing would certainly fix it (just a single space would even be enough).

On OS/X for example the most-left pixels are literally the border of your terminal (unless your terminal itself has an explicit margin). It would be nice if ugrep could either by default or optionally prepend a space before at each line.

**Comment by hackerb9** [comment]
I haven't used a Mac in a while, but this sounds very odd to me. Why would Apple remove the margins? White space is not "nothing" and can't be optimized away. I hope Contour on MacOS has some white space. Yes?

It seems like the right fix would be for Apple to add the padding back into Terminal.app. But, since I have little sway over what they do, I've patched ugrep to add three spaces.

**Comment by christianparpart** [comment]
> I haven't used a Mac in a while, but this sounds very odd to me. Why would Apple remove the margins? White space is not "nothing" and can't be optimized away. I hope Contour on MacOS has some white space. Yes?
> 
> It seems like the right fix would be for Apple to add the padding back into Terminal.app. But, since I have little sway over what they do, I've patched ugrep to add three spaces.

Standard unconfigurable loading up until hopefully only very soon. I will check against others defaults seeing. So no need to act immediately. I will ping you with the updates.

**Comment by hackerb9** [comment]
I think this is fixed, so I'm closing the bug. If I am mistaken, please don't hesitate to reopen it.
